import {PrismaClient} from '@prisma/client';
import {encryptPassword, generateActivationToken} from '../models/user';

export async function addUsers(prisma: PrismaClient): Promise<any> {
    return prisma.user.createMany({
        data: [{
                fullName: "Admin",
                phone: "+380000000000",
                city: "Dnepr",
                email: "admin@gmail.com",
                activationToken: generateActivationToken(),
                passwordHash: await encryptPassword("123456789"),
                status: "ACTIVE",
                roleId: 1,
                banReason: null,
                createdAt: new Date(),
                resetPasswordToken: null,
                googleId: null,
            }, {
                fullName: "Manager",
                phone: "+380000000000",
                city: "Dnepr",
                email: "manager@gmail.com",
                activationToken: generateActivationToken(),
                passwordHash: await encryptPassword("123456789"),
                status: "ACTIVE",
                roleId: 2,
                banReason: null,
                createdAt: new Date(),
                resetPasswordToken: null,
                googleId: null,
            }, {
                fullName: "Customer",
                phone: "+380000000000",
                city: "Dnepr",
                email: "customer@gmail.com",
                activationToken: generateActivationToken(),
                passwordHash: await encryptPassword("123456789"),
                status: "ACTIVE",
                roleId: 3,
                banReason: null,
                createdAt: new Date(),
                resetPasswordToken: null,
                googleId: null,
            }, {
                fullName: "GoverningManager",
                phone: "+380000000000",
                city: "Dnepr",
                email: "governing.manager@gmail.com",
                activationToken: generateActivationToken(),
                passwordHash: await encryptPassword("123456789"),
                status: "ACTIVE",
                roleId: 4,
                banReason: null,
                createdAt: new Date(),
                resetPasswordToken: null,
                googleId: null,
            }, {
                fullName: "BannerManager",
                phone: "+380000000000",
                city: "Dnepr",
                email: "banner.manager@gmail.com",
                activationToken: generateActivationToken(),
                passwordHash: await encryptPassword("123456789"),
                status: "ACTIVE",
                roleId: 5,
                banReason: null,
                createdAt: new Date(),
                resetPasswordToken: null,
                googleId: null,
            }],
        skipDuplicates: true
    });
}
